/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.dao.Conexao;
import fatec.poo.dao.DaoCliente;
import fatec.poo.dao.DaoPedido;
import fatec.poo.dao.DaoProduto;
import fatec.poo.dao.DaoVendedor;
import fatec.poo.dao.DaoItemPedido;
import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicListUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class GuiPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiPedido
     */
    public GuiPedido() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumPed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxtDataPed = new javax.swing.JFormattedTextField();
        try{ 
            javax.swing.text.MaskFormatter data = new javax.swing.text.MaskFormatter("##/##/####"); 
            ftxtDataPed = new javax.swing.JFormattedTextField(data); 
        } 
        catch (Exception e){ 
        }
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ftxtCPFCliente = new javax.swing.JFormattedTextField();
        try{ 
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##"); 
            ftxtCPFCliente = new javax.swing.JFormattedTextField(cpf); 
        } 
        catch (Exception e){ 
        }
        btnPesqCliente = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ftxtCPFVendedor = new javax.swing.JFormattedTextField();
        try{ 
            javax.swing.text.MaskFormatter cpf = new javax.swing.text.MaskFormatter("###.###.###-##"); 
            ftxtCPFVendedor = new javax.swing.JFormattedTextField(cpf); 
        } 
        catch (Exception e){ 
        }
        btnPesqVendedor = new javax.swing.JButton();
        lblNomeVendedor = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodProd = new javax.swing.JTextField();
        btnPesqProduto = new javax.swing.JButton();
        lblDescricaoProduto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtQtdeVend = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnRmvItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalPedido = new javax.swing.JLabel();
        lblQtdeItens = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Emitir Pedido");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        jLabel1.setText("Número do Pedido:");

        txtNumPed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumPedFocusLost(evt);
            }
        });

        jLabel2.setText("Data do Pedido:");

        ftxtDataPed.setEnabled(false);
        ftxtDataPed.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtDataPedFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtDataPed, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtDataPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jLabel3.setText("CPF do Cliente:");

        ftxtCPFCliente.setEnabled(false);

        btnPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        btnPesqCliente.setEnabled(false);
        btnPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqClienteActionPerformed(evt);
            }
        });

        lblNomeCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesqCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnPesqCliente)
                            .addComponent(ftxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Vendedor"));

        jLabel4.setText("CPF do Vendedor:");

        ftxtCPFVendedor.setEnabled(false);

        btnPesqVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        btnPesqVendedor.setEnabled(false);
        btnPesqVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqVendedorActionPerformed(evt);
            }
        });

        lblNomeVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesqVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblNomeVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnPesqVendedor)
                            .addComponent(ftxtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel5.setText("Código do Produto:");

        txtCodProd.setEnabled(false);

        btnPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/consultar.png"))); // NOI18N
        btnPesqProduto.setEnabled(false);
        btnPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqProdutoActionPerformed(evt);
            }
        });

        lblDescricaoProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setText("Qtde. Vendida:");

        txtQtdeVend.setEnabled(false);

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add_item.png"))); // NOI18N
        btnAddItem.setMnemonic('A');
        btnAddItem.setText("Adicionar Item");
        btnAddItem.setEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRmvItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rmv_item.png"))); // NOI18N
        btnRmvItem.setMnemonic('R');
        btnRmvItem.setText("Remover Item");
        btnRmvItem.setEnabled(false);
        btnRmvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvItemActionPerformed(evt);
            }
        });

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Preço Unitário", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProdutos.getTableHeader().setReorderingAllowed(false);
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total do Pedido:");

        jLabel8.setText("Qtde. de Itens:");

        lblTotalPedido.setText("0");
        lblTotalPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lblQtdeItens.setText("0");
        lblQtdeItens.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txtQtdeVend, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnRmvItem))
                            .addComponent(lblDescricaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPedido))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblQtdeItens)))))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblQtdeItens, lblTotalPedido, txtQtdeVend});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesqProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDescricaoProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQtdeVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem)
                    .addComponent(btnRmvItem))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(lblTotalPedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(lblQtdeItens))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblQtdeItens, lblTotalPedido, txtQtdeVend});

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/alterar.png"))); // NOI18N
        btnAlterar.setMnemonic('A');
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/excluir.png"))); // NOI18N
        btnExcluir.setMnemonic('E');
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/sair.png"))); // NOI18N
        btnSair.setMnemonic('S');
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/incluir.png"))); // NOI18N
        btnIncluir.setMnemonic('I');
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_btnSairActionPerformed

    private void ftxtDataPedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtDataPedFocusLost
        String s = ftxtDataPed.getText();
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        df.setLenient(false); // aqui o pulo do gato  
        try {
            // data válida
            df.parse(s);
            ftxtDataPed.setEnabled(false);
            ftxtCPFCliente.setEnabled(true);
            txtQtdeVend.setEnabled(false);
            btnPesqCliente.setEnabled(true);

            ftxtCPFCliente.requestFocus();

            ftxtCPFCliente.setText("14426334764");//APAGAR
            ftxtCPFVendedor.setText("15622225973");//APAGAR
        } catch (ParseException ex) {
            // data inválida
            JOptionPane.showMessageDialog(null, "Informe uma data válida", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ftxtDataPedFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao = new Conexao("JEFFERSON", "jefferson");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoPedido = new DaoPedido(conexao.conectar());
        daoCliente = new DaoCliente(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoProduto = new DaoProduto(conexao.conectar());

        txtNumPed.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        pedido = new Pedido(Integer.parseInt(txtNumPed.getText()), ftxtDataPed.getText());
        pedido.setCliente(cliente);
        pedido.setVendedor(vendedor);
        pedido.setStatus(0); //Em aberto
        daoPedido.inserir(pedido);

        limparCampos();
        btnIncluir.setEnabled(false);
        txtNumPed.setEnabled(true);
        ftxtDataPed.setEnabled(false);
        ftxtCPFCliente.setEnabled(false);
        ftxtCPFVendedor.setEnabled(false);
        txtCodProd.setEnabled(false);
        txtQtdeVend.setEnabled(false);
        btnAddItem.setEnabled(false);
        btnRmvItem.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        DefaultTableModel tabelaProdutos = (DefaultTableModel) tblProdutos.getModel();
        tabelaProdutos.setNumRows(0);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (tblProdutos.getRowCount() > 0) {
            JOptionPane.showMessageDialog(null, "Remova todos os itens do pedido antes de cancelá-lo!", "Erro", JOptionPane.ERROR_MESSAGE);
        } else {
            conexao.fecharConexao();
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void txtNumPedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumPedFocusLost
        pedido = null;
        if (!campoNumerico(txtNumPed.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Digite somente números!");
            txtNumPed.setText("");
            txtNumPed.requestFocus();
        } else {
            pedido = daoPedido.consultar(Integer.parseInt(txtNumPed.getText()));

            if (pedido == null) { //Se o pedido não existir
                ftxtDataPed.setEnabled(true);

                btnIncluir.setEnabled(true);
                btnPesqVendedor.setEnabled(false);
                btnAlterar.setEnabled(false);
                btnExcluir.setEnabled(false);

                txtNumPed.setEnabled(false);

                Date hoje = new Date();
                SimpleDateFormat df;
                df = new SimpleDateFormat("dd/MM/yyyy");
                ftxtDataPed.setText(df.format(hoje));
                ftxtDataPed.requestFocus();
            } else { //Se o Pedido já existir
                txtNumPed.setText(String.valueOf(pedido.getNumero()));
                txtNumPed.setEnabled(false);
                ftxtDataPed.setText(pedido.getDataEmissaoPedido());
                ftxtDataPed.setEnabled(false);
                ftxtCPFCliente.setText(pedido.getCliente().getCpf());
                lblNomeCliente.setText(pedido.getCliente().getNome());

                ftxtCPFVendedor.setText(pedido.getVendedor().getCpf());
                lblNomeVendedor.setText(pedido.getVendedor().getNome());
            }
        }
    }//GEN-LAST:event_txtNumPedFocusLost

    private void btnPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqClienteActionPerformed
        cliente = null;
        cliente = daoCliente.consultar(ftxtCPFCliente.getText().replace(".", "").replace("-", ""));

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado. Re-digite o CPF.", "ERRO", JOptionPane.ERROR_MESSAGE);
            lblNomeCliente.setText("");
            ftxtCPFCliente.setText("");
            ftxtCPFCliente.requestFocus();
        } else {
            lblNomeCliente.setText(cliente.getNome());
            ftxtCPFCliente.setEnabled(false);
            btnPesqCliente.setEnabled(false);
            ftxtCPFVendedor.setEnabled(true);
            btnPesqVendedor.setEnabled(true);
            ftxtCPFVendedor.requestFocus();
        }

    }//GEN-LAST:event_btnPesqClienteActionPerformed

    private void btnPesqVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqVendedorActionPerformed
        vendedor = null;
        vendedor = daoVendedor.consultar(ftxtCPFVendedor.getText().replace(".", "").replace("-", ""));

        if (vendedor == null) {
            JOptionPane.showMessageDialog(null, "Vendedor não encontrado. Re-digite o CPF.", "ERRO", JOptionPane.ERROR_MESSAGE);
            lblNomeVendedor.setText("");
            ftxtCPFVendedor.setText("");
            ftxtCPFVendedor.requestFocus();
        } else {
            lblNomeVendedor.setText(vendedor.getNome());
            txtCodProd.requestFocus();
            ftxtCPFVendedor.setEnabled(false);
            btnPesqVendedor.setEnabled(false);
            btnPesqProduto.setEnabled(true);
            txtCodProd.setEnabled(true);
        }
    }//GEN-LAST:event_btnPesqVendedorActionPerformed

    private void btnPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqProdutoActionPerformed
        produto = null;
        produto = daoProduto.consultar(Integer.parseInt(txtCodProd.getText()));

        if (produto == null) {
            JOptionPane.showMessageDialog(null, "Produto não encontrado. Re-digite o código.", "ERRO", JOptionPane.ERROR_MESSAGE);
            lblDescricaoProduto.setText("");
            txtCodProd.setText("");
            txtCodProd.requestFocus();
        } else {
            lblDescricaoProduto.setText(produto.getDescricao());
            txtQtdeVend.setEnabled(true);
            btnAddItem.setEnabled(true);
            txtQtdeVend.requestFocus();
        }
    }//GEN-LAST:event_btnPesqProdutoActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        DefaultTableModel modTblProd;
        modTblProd = (DefaultTableModel) tblProdutos.getModel();
        produto = null;
        if (!campoNumerico(txtCodProd.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Digite somente números válidos!");
            txtCodProd.setText("");
            txtCodProd.requestFocus();
        } else {
            produto = daoProduto.consultar(Integer.parseInt(txtCodProd.getText()));

            if (!campoNumerico(txtQtdeVend.getText()) || Integer.parseInt(txtQtdeVend.getText()) < 1) {
                JOptionPane.showMessageDialog(rootPane, "Digite somente números válidos!");
                txtQtdeVend.setText("");
                txtQtdeVend.requestFocus();
            } else {
                if (produto.getQtdDisponivel() < Integer.parseInt(txtQtdeVend.getText())) {
                    JOptionPane.showMessageDialog(null, "Quantidade em estoque inferior à quantidade vendida. Re-digite a quantidade.", "Erro", JOptionPane.ERROR_MESSAGE);
                    txtQtdeVend.setText("");
                    txtQtdeVend.requestFocus();
                } else {
                    item = new ItemPedido(Integer.parseInt(lblQtdeItens.getText()) + 1, Integer.parseInt(txtQtdeVend.getText()));
                    item.setProduto(produto);
                    item.setPedido(pedido);

                    pedido.addItemPedido(item);
                    if (item == null) {
                        System.out.println("Item Nulão 2.1 ");
                    }
                    lblTotalPedido.setText(String.valueOf(Double.parseDouble(lblTotalPedido.getText()) + Double.parseDouble(txtQtdeVend.getText()) * produto.getPrecoUnit()));
                    //lblQtdeItens.setText(String.valueOf(modTblProd.getRowCount() + 1));
                    lblQtdeItens.setText(String.valueOf(Integer.parseInt(lblQtdeItens.getText()) + 1));

                    //produto.setQtdDisponivel(produto.getQtdDisponivel() - Integer.parseInt(txtQtdeVend.getText()));
                    if (produto.getQtdDisponivel() <= produto.getEstoqueMin()) {
                        JOptionPane.showMessageDialog(null, "O produto está com estoque mínimo ou abaixo dele", "Aviso", JOptionPane.WARNING_MESSAGE);
                    }
                    if (item == null) {
                        System.out.println("Item Nulão 3");
                    } else {
                        daoItemPedido.inserir(item);
                    }

                    String linha[] = {
                        String.valueOf(produto.getCodigo()),
                        produto.getDescricao(),
                        txtQtdeVend.getText(),
                        String.valueOf(produto.getPrecoUnit()),
                        String.valueOf(Integer.parseInt(txtQtdeVend.getText()) * produto.getPrecoUnit())
                    };
                    modTblProd.addRow(linha);
                    txtCodProd.setText("");
                    txtCodProd.requestFocus();
                    lblDescricaoProduto.setText("");
                    txtQtdeVend.setText("");
                    btnAddItem.setEnabled(false);
                    btnRmvItem.setEnabled(false);
                }
            }
        }
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRmvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvItemActionPerformed
        DefaultTableModel modTblProd;
        modTblProd = (DefaultTableModel) tblProdutos.getModel();
        produto = null;
        produto = daoProduto.consultar(Integer.parseInt(String.valueOf(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0))));
        produto.setQtdDisponivel(produto.getQtdDisponivel() + Integer.parseInt(String.valueOf(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 2))));
        lblTotalPedido.setText(String.valueOf(Double.parseDouble(lblTotalPedido.getText()) - Double.parseDouble(String.valueOf(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 4)))));
        lblQtdeItens.setText(String.valueOf(Integer.parseInt(lblQtdeItens.getText()) - 1));
        modTblProd.removeRow(tblProdutos.getSelectedRow());
    }//GEN-LAST:event_btnRmvItemActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
        int linhaSelecionada = tblProdutos.getSelectedRow();
        txtCodProd.setText(String.valueOf(tblProdutos.getValueAt(linhaSelecionada, 0)));
        lblDescricaoProduto.setText(produto.getDescricao());
        txtQtdeVend.setText(String.valueOf(tblProdutos.getValueAt(linhaSelecionada, 2)));
        btnRmvItem.setEnabled(true);
    }//GEN-LAST:event_tblProdutosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesqCliente;
    private javax.swing.JButton btnPesqProduto;
    private javax.swing.JButton btnPesqVendedor;
    private javax.swing.JButton btnRmvItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JFormattedTextField ftxtCPFCliente;
    private javax.swing.JFormattedTextField ftxtCPFVendedor;
    private javax.swing.JFormattedTextField ftxtDataPed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNomeVendedor;
    private javax.swing.JLabel lblQtdeItens;
    private javax.swing.JLabel lblTotalPedido;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCodProd;
    private javax.swing.JTextField txtNumPed;
    private javax.swing.JTextField txtQtdeVend;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        URL url = this.getClass().getResource("/fatec/poo/view/icon/pedido.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    private void limparCampos() {
        txtNumPed.setText("");
        txtCodProd.setText("");
        txtQtdeVend.setText("");
        ftxtCPFCliente.setText("");
        ftxtCPFVendedor.setText("");
        ftxtDataPed.setText("");
        lblNomeCliente.setText("");
        lblNomeVendedor.setText("");
        lblDescricaoProduto.setText("");
        lblTotalPedido.setText("");
        lblQtdeItens.setText("");
    }

    private Conexao conexao = null;
    private Cliente cliente = null;
    private Vendedor vendedor = null;
    private Produto produto = null;
    private Pedido pedido = null;
    private ItemPedido item = null;
    private DaoCliente daoCliente = null;
    private DaoVendedor daoVendedor = null;
    private DaoProduto daoProduto = null;
    private DaoPedido daoPedido = null;
    private DaoItemPedido daoItemPedido = null;

    private boolean campoNumerico(String campo) {
        return campo.matches("[0-9]+");
    }

    private boolean isNulo(Object o) {
        if (o == null) {
            return true;
        } else {
            return false;
        }
    }

}
